# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18e628deb111c8c7c821fca3d4ea1720a1bac54f136885fc04e16d5df86d7be7f7df4f928c81b6755059964c64449ea0be353423981e8bb09945129b1649bdc

test:
  secret_key_base: f7a62702ba024095deb54b1f5b6605b1a6115281bfddccb6254e1df82a3783ca54f401f41ee5a78c95230b4bf98dedfc440ccde491977d3b93927b654b275960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
